### PR TITLE
Bump hedgehog upper bound

### PR DESCRIPTION
**Pull request by gwils**

### CODE REVIEW

**Comment by gwils** [comment]
@newhoggy  Please make a metadata revision to the latest hw-dsv

**Comment by newhoggy** [comment]
Thanks!  I'm waiting to confirm that it is actually building with the latest `hedgehog`

**Comment by newhoggy** [comment]
This build shows that it is using `hedgehog-1.0`:

https://circleci.com/gh/haskell-works/hw-dsv/948

**Comment by newhoggy** [comment]
New metadata revision pushed.

**Comment by newhoggy** [comment]
Thanks again!

**Pull request merged**
