### PR TITLE
Make the lazy cursor no longer depend on a terminal newline

### PR DESCRIPTION
**Pull request by gwils**
Previously a terminal newline was required for the lazy
cursor to work. This change makes it work with or without
a terminal newline.

What do you think of this? I'm happy to change parameter names or whatever. I'm keen to hear what you think of the implementation. Performance-sensitive stuff isn't my forte, so this might not be ideal.

I've also added some tests. Note that one of them is commented out because it is an edge case that does not work. The CSV file: "\n". I don't think it's a very useful CSV file anyway. What do you think about that?

### CODE REVIEW

**Comment by newhoggy** [comment]
What's the expected behaviour when the file terminates with `'\n'`?

**Comment by gwils** [comment]
As the tests show, the behaviour should be the same with or without a terminating newline, except in an unfortunate edge-case which has a commented-out test.

**Comment by newhoggy** [comment]
It seems to be marginally slower, but with the jitter, I can't be sure.  The possible performance penalty of the change may not be anything to be overly concerned about.

On `master`:

```
$ cat ~/arbornetwrks_v888_20180503.csv | pv -t -e -b -a | hw-dsv query-lazy -k 0 -k 1 -d , -e '|' > /dev/null
7.08GiB 0:00:45 [ 160MiB/s]
$ cat ~/arbornetwrks_v888_20180503.csv | pv -t -e -b -a | hw-dsv query-lazy -k 0 -k 1 -d , -e '|' > /dev/null
7.08GiB 0:00:44 [ 163MiB/s]
```

On `optional-terminal-newline`:

```
$ cat ~/arbornetwrks_v888_20180503.csv | pv -t -e -b -a | hw-dsv query-lazy -k 0 -k 1 -d , -e '|' > /dev/null
7.08GiB 0:00:45 [ 158MiB/s]
$ cat ~/arbornetwrks_v888_20180503.csv | pv -t -e -b -a | hw-dsv query-lazy -k 0 -k 1 -d , -e '|' > /dev/null
7.08GiB 0:00:44 [ 162MiB/s]
```

**Comment by newhoggy** [comment]
Regarding the case that doesn't work, it sounds trivial to test if the file is actually the single failing case and return the correct result in that case and not even invoke the CSV parsing.

I'm happy to merge the change as is and if anyone raises a concern we can patch that case.

**Comment by gwils** [comment]
Thanks mate!

**Pull request merged**
