### PR TITLE
Weigh lazy cassava/hw-dsv

### PR DESCRIPTION
**Pull request by gwils**
I think weighing these too is a good idea. What do you reckon about that? Do you think this is the right way to measure these?

### CODE REVIEW

**Comment by newhoggy** [comment]
I haven't put enough though into this.  Is weighing a `Vector` of `Vector` the best way to do to it for streaming?  For example is it more appropriate to use `[]` of `Vector` and the force evaluate it on a row-by-row basis?

**Comment by gwils** [comment]
Hm, I think you're right. I'll change this in the morning to not build a vector. Should I do the same in #15? We're also constructing a vector there in both cassava and hw-dsv lazy cases.

**Comment by gwils** [comment]
```
Case                Allocated     Max    Live  GCs
Vector ByteString   8,249,640   9,664  15,816    4
Vector ByteString  11,460,920   9,976  16,824    7
Vector ByteString   6,413,080     808   7,152    6
Vector ByteString  10,634,864  41,456  48,160    9
```

Also I think I will change these so that the labels are distinct.

**Comment by gwils** [comment]
```
Case                Allocated     Max    Live  GCs
cassava strict      8,249,656   9,664  14,616    4
cassava streaming  11,460,816   9,976  15,456    7
hw-dsv strict       6,412,976     808   5,952    6
hw-dsv lazy        10,634,760  41,456  46,792    9
```

**Comment by newhoggy** [comment]
Yeah, I think something that traverses the `[Vector ByteString]` and touches every `ByteString`.

Perhaps summing the length of all the `ByteString`s should be enough to force evaluate everything.

**Comment by gwils** [comment]
`weigh` uses `force` from `Control.Deepseq` so I don't think we need to do anything like that.

**Pull request merged**
